services:
  - type: web
    name: taskmanager
    env: python
    rootDirectory: .
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: PYTHON_VERSION
        value: "3.12.10"
